# Generated by Django 4.1.3 on 2022-12-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
    ]
