# Generated by Django 4.1.3 on 2022-12-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'AboutUs', 'verbose_name_plural': 'AboutUs'},
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='blogs/static/blogs/img/user.png', upload_to='user/'),
        ),
    ]
